### ISSUE TITLE
About the GPU memory

### ISSUE THREAD

**Issue by lz20061213** [sfzhang15/RefineDet#27]
I  changed the gpus for a single one and run the script `examples/refinedet/VGG16_VOC2007_320.py` in GTX 1080 Ti (11G), but it turned out `out of memory` error . Does it need more than 11G GPU memory?

**Comment by sfzhang15** [comment]
@lz20061213 , Hi
By default, we use four GPUs (12G) with 32 batch size, so every GPU have 8 images. If you change the gpus for a single one, you should change the 'batch_size=32' correspondingly. Maybe 'batch_size=16' or 'batch_size=8' will run successfully. Because 32 images are too many for one 11G GPU.

**Comment by lz20061213** [comment]
@sfzhang15 Hi, thanks for your reply! I wonder if i change the batch_size to solve the GPU memory problem, should i change the `max_iter` and `stepvalue` at the same time?

**Comment by sfzhang15** [comment]
@lz20061213 Hi, you do not need to change other parameters. Since the 'accum_batch_size' is unchanged. If you change the 'batch_size' form 32 to 8, the 'iter_size' of four GPUs is 1, while the 'iter_size' of one GPU will become 4. But the accum_batch_size is the same, i.e., accum_batch_size=32.

**Comment by lz20061213** [comment]
@sfzhang15 Got it! Truly thanks!
