### ISSUE TITLE
The amount relationship of two location loss

### ISSUE THREAD

**Issue by zhujiagang** [sfzhang15/RefineDet#35]
Hi, Mr Zhang. A wonderful work you have done!
I am very curious about the two location losses in arm and odm. Is there any relationship between their amount? For example, the location in arm is coarser than that of odm. So perhaps the location loss of odm is smaller than that of arm (without considering their prediction). I also tried to display these two losses and found that it was not the case. One of these two terms is bigger than the other with almost the same chance (or location loss of odm is bigger than that of arm). I also observed that the number of postive match of odm is almost always bigger than that of arm.

 In my opinion, the differences between these two losses come from
1 different predictions due to different feature and initialization, and the resultant number of positive and negative match
2 odm receives filtered and refined boxes from arm as its prior boxes

**Comment by sfzhang15** [comment]
@zhujiagang Hi, thank you for your interest in our work. We have not compared the regression loss between ARM and ODM, since SSD displays the classification loss and regression loss together and we do not modify it. In our opinion, maybe there is no fixed relationship between them. ARM and ODM use the same IoU threshold (i.e., 0.5) to choose positive anchors, and ODM receives refined boxes from arm as its prior boxes. Suppose they have exactly the same positive anchors in number and location, the regression loss of ODM must be smaller than that of ARM. But as you observed, the number of positive anchors of ODM is always bigger than that of ARM, since ODM always has some newly positive anchors, which are not matched in ARM. It means that because of the regression impact of ARM, ODM can always match some newly positive anchors with large location offset, which maybe result ODM in bigger regression  loss than ARM.  This is also one of the points we will try to improve, i.e., ARM and ODM have progressive IoU threshold.
