### ISSUE TITLE
Aspect Ratios

### ISSUE THREAD

**Issue by PetreanuAndi** [sfzhang15/RefineDet#89]
In the paper you say u use 3 aspect ratios ("  (i.e.,0.5,1.0,  and2.0). " ) but in the code it seems like there is only one aspect ratio associated with every source_layer / min_size / max_size / step : 

arm_source_layers = ['res3b3_relu', 'res4b22_relu', 'res5c_relu', 'res6_relu']
odm_source_layers = ['P3', 'P4', 'P5', 'P6']
min_sizes = [32, 64, 128, 256] 
max_sizes = [[], [], [], []]
steps = [8, 16, 32, 64]
**aspect_ratios = [[2.0], [2.0], [2.0], [2.0]]**

Moreover, if I try to change these aspect ratios to [[0.5], [1.0], [2.0], [3.0]], there is an assert error message that suggests shapes no longer match in the network.

I got it to work with **aspect_ratios = [[0.5], [0.5], [2.0], [2.0]]**, but I am wondering how I can stay as close as possible to the paper literature, aka. **aspect_ratios = [[0.5], [1.0], [2.0], [2.0]]**

Results on [512,512], 1Titan GPU, 2 batch-size, 6 classes, default augmentation (flipping + distortion), 20 epochs, are _much lower than Faster RCNN counterpart_, and pretty similar to plain old SSD.

Am I doing something wrong? Any tips / tricks are appreciated.

**Comment by sfzhang15** [comment]
@PetreanuAndi 
1. You can refer to [prior_box_layer.cpp](https://github.com/sfzhang15/RefineDet/blob/master/src/caffe/layers/prior_box_layer.cpp) for details about generating anchors, i.e., aspect_ratio=2 means it has 3 aspect_ratios (1/2, 1, 2), since 1 is default and 2 will be flipped to get 1/2.

2. If you set aspect_ratio = [[0.5], [1.0], [2.0], [3.0]] with flip = true, there are 5 aspect_ratios (1, 1/2, 2, 1/3, 3). You can set aspect_ratio = [[0.5], [1.0], [2.0], [3.0]] with flip = false to get 4 aspect_ratios (1, 0.5, 2, 3).
